[package]
name = "anni-workspace"
version = "0.1.0"
authors = ["Yesterday17 <mmf@mmf.moe>"]
edition = "2021"

[dependencies]
anni-repo = { path = "../anni-repo", features = ["git", "flac"] }
anni-common = { path = "../anni-common" }

uuid = { version = "1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
thiserror = "1"
toml = "0.7.0"
